In [1]:
import numpy as np

In [3]:
a = np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0, 8.0, 7.0],[6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
print(a.ndim)
print(b.shape)
print(a.dtype)

1
(2, 3)
int32


In [8]:
print(a.itemsize)
print(a.nbytes)
print(a.size)


4
12
3


In [11]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
t = a
u = a.copy()

t[0,0] = 10
print(a)

[[10  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
a[:,2]

array([ 3, 10])

In [14]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:-1:2]
a[1,1::3]

array([ 9, 12])

In [29]:
np.random.seed(37)
randarr = np.array([np.random.randint(1,101) for i in range(1,101)])
randarr[:5]
len(randarr)
randarr[np.argsort(randarr)[-10:]] # 10 largest numbers

array([ 91,  93,  94,  94,  96,  98,  99,  99, 100, 100])

TypeError: only integer scalar arrays can be converted to a scalar index