## Saurabh Kumar Singh
## 25-27-05

## Q1. Generate 1000 integers between 1 and 100, find mean and sd, count how many vals are above 50. 

In [5]:
import numpy as np

arr = np.random.randint(1,101,size=1000)
print(f"Hightest value : {max(arr)}")
print(f"Lowest value: {min(arr)}")
print(f"Standard Deviation: {np.std(arr)}")
print(f"Mean: {np.mean(arr)}")
print(f"Median: {np.median(arr)}")

print(f"Values >50: {len([i for i in arr if i > 50])}")
print(f"value > 50: {np.sum(arr > 50)}")

Hightest value : 100
Lowest value: 1
Standard Deviation: 29.497734082468096
Mean: 50.678
Median: 50.0
Values >50: 498
value > 50: 498


## Q2. Write a functino that takes two numpy arrays of the same shape and returns a new array containing the element wise sum, difference, product and quotient

    a = np.array([10,20,30])
    b = np.array([1,2,3])

In [6]:
def array_sum_diff_prod_quot(a,b):
    if len(a) != len(b):
        return AssertionError("both vectors should be of same length")
    
    sum = a + b
    diff = a - b
    prod = a * b
    quot = a / b
    
    return [sum, diff, prod, quot]


a = np.array([10,20,30])
b = np.array([1,2,3])

print(array_sum_diff_prod_quot(a,b))

[array([11, 22, 33]), array([ 9, 18, 27]), array([10, 40, 90]), array([10., 10., 10.])]


## Q3. Create two 2D arrays(metrices) and perform matrix multiplication. Then return transpose of the result. 

    A = np.array([[1,2], [3,4]])
    B = np.array([[5,6], [7,8]])

In [7]:
def multiply_return_transpose(a,b) : 
    return np.transpose(np.multiply(a,b))

A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [7,8]])

print(multiply_return_transpose(A,B))

[[ 5 21]
 [12 32]]


## Q4. Write a function that finds the value in a numpy array that is closest to the given target number. 

    arr = np.array([10,22,37,41, 55])
    target = 40

In [14]:
def find_closest(arr, target):
    closest = arr[0]
    min_diff = abs(closest - target)
    for i,num in enumerate(arr):
        diff = abs(num - target)
        if diff < min_diff:
            min_diff = diff
            closest = arr[i]
            print("new closest : " , closest)
    return closest
        


print(find_closest(arr = np.array([10,22,37,41, 55]), target=40))

new closest :  22
new closest :  37
new closest :  41
41


## Q5. Given a 1D numpy array of temperature readings, replace any value that is more than 2SD away from the mean with the mean value of the array. 

    arr = np.array([22,23,21,24,100,22,23,-50,25])

Expected output: an array where outliers such as -50, 100 are replaced by the mean of the OG array

In [20]:
arr = np.array([22,23,21,24,100,22,23,-50,25])

mean = np.mean(arr)
sd = np.std(arr)
sdx2 = sd * 2

for i, num in enumerate(arr):
    if abs(num - mean) > sdx2:
        arr[i] = mean

print(arr)

[22 23 21 24 23 22 23 23 25]


## Q7. Group alist of strings into anagram groups

    words = ["eat", "tea", "tan", "ate", "nat", "bat"]
    Output: [["bat"],["nat","tan"],["ate","eat","tea"]]

## Q8. Generate a 4x4 numpy array of random integers between 1 and 20, replace all elements that are divisible by 3 with their squares and set all elements less than 5 to 0. Return the modified array

In [32]:
arr4x4 = np.random.randint(1, 21, size=16).reshape(4,4)
print(arr4x4)

for i in range(4):
    for j in range(4):
        element = arr4x4[i,j]
        if element % 3 == 0:
            arr4x4[i,j] = element ** 2
        if element < 5:
            arr4x4[i,j] = 0

print(arr4x4)

[[10 10 11 15]
 [10  4 11  4]
 [ 3 17 15 15]
 [17 19 13 19]]
[[ 10  10  11 225]
 [ 10   0  11   0]
 [  0  17 225 225]
 [ 17  19  13  19]]


## Q9. Generate a 3x5 numpy array of floating point numbers, normalize each row such that the sum of elements in each row equals 1(ie, convert each row to a probability distribution). If a row sums to 0, leave it unchanged. 

In [38]:
arr3x5 = np.random.rand(3,5)
print(arr3x5)

for i in range(3):
    rowsum = np.sum(arr3x5[i,:])
    if rowsum != 0:
        arr3x5[i,:] = arr3x5[i,:] / rowsum
print(arr3x5)

[[0.35682432 0.01268507 0.37604064 0.604567   0.68769856]
 [0.16179863 0.70643961 0.62404687 0.17739363 0.80779809]
 [0.57879636 0.26519332 0.03326321 0.86097381 0.17340753]]
[[0.17510138 0.00622484 0.18453124 0.29667405 0.33746849]
 [0.06530783 0.28514479 0.25188807 0.07160254 0.32605677]
 [0.30277569 0.13872597 0.01740041 0.45038627 0.09071167]]


## Q10. Given two 4x4 numpy arrays A and B containing integers, compute the matrix product A, B. Then calculate the mean of all elements in the resulting matrix using : for each element in the product matrix, if it is greater than mean, multiply it by 3, othersise, divide it by 3. Return the modified matrix. 

In [51]:
np.random.seed(37)

arr1 = np.random.randint(1,21,size=16).reshape(4,4)
arr2 = np.random.randint(1,21,size=16).reshape(4,4)

print(arr1)
print(arr2)

prod = np.matmul(arr1,arr2)
print("Prod" , prod)

mean = np.mean(prod)
print("Mean", mean)

modified = np.where(prod > mean , prod * 3, prod/3)
print(modified)

[[16 12 13  4]
 [ 4 11  9  9]
 [ 4 19 13 15]
 [13 18 20 18]]
[[11  4  3 20]
 [ 4  3  4  8]
 [15 15  2 11]
 [20 18  4 12]]
Prod [[499 367 138 607]
 [403 346 110 375]
 [615 538 174 555]
 [875 730 223 840]]
Mean 462.1875
[[1497.          122.33333333   46.         1821.        ]
 [ 134.33333333  115.33333333   36.66666667  125.        ]
 [1845.         1614.           58.         1665.        ]
 [2625.         2190.           74.33333333 2520.        ]]
