# Implementing algorithm to reduce a given $m \times n$ matrix into it's Row-Echelon Form

### Environment setup and smoke check

In [ ]:
#Importing the required libraries and running a smoke test
try: 
    import numpy as np
    import sympy as sp
    
    print('numpy is installed and imported successfully')
    print(f'Version: {np.__version__}')
    
    print('sympy is installed and immport successfully')
    print(f"Version: {sp.__version__}")
    
    test_matrix = np.array([
        [1,2,3],
        [4,5,6],
    ])
    
    print("matrix creating successfull")
    print(test_matrix)
    sp.pprint(sp.Matrix(test_matrix))
except ImportError as e:
    print(e.msg)

## Row-Echelon form
A matrix is in row-echelon form if it satisfies the two conditions: 
1. All rows consisting entirely of zeros are the the bottom of the matrix. 
2. The first non-zero number from the left of any non-zero row (called the ***pivot***) is to the right of the pivot of the row above it.

This structure creates a "staircase" pattern of leading non-zero entries. The goal of the algorithm is to use **Gaussian-Elimination** using **Elementary-Row Operations** to create zeros below each pivot.

### Example

$$
    \begin{bmatrix}
    1 & 2 & 3 \\
    2 & 3 & 5 \\
    3 & 7 & 6
    \end{bmatrix}

    \;\;\longrightarrow\;\;

    \begin{bmatrix}
    1 & 2 & 3 \\
    0 & -1 & -1 \\
    0 & 0 & -4
    \end{bmatrix}
$$




## First attempt it for a $3 \times 3$ matrix and later generalize the procedure

In [ ]:
# A test matrix who's result is already known
A = np.array([
    [1, 2, 3],
    [2, 3, 5],
    [3, 7, 6],
])
sp.pprint(sp.Matrix(A))

⎡1  2  3⎤
⎢       ⎥
⎢2  3  5⎥
⎢       ⎥
⎣3  7  6⎦


In [42]:
B = np.array(A, dtype=np.float64) # commas separate the dimensions, and colons give the range.
B[1, :] = B[1, :] - (B[1, 0]/(B[0,0])) * (B[0,:])
B[2, :] = B[2, :] - (B[2, 0]/(B[0,0])) * (B[0,:])

B[2, :] = B[2, :] - (B[2, 1]/(B[1,1])) * (B[1,:])
assert B.shape == (3,3)

In [35]:
# putting the above logic into a function which takes 3x3 array as an input
def reduce_row_echelon3x3(A):
    """Takes a 3x3 matrix as input, and reduces it into it's row echelon form"""
    B = np.array(A, dtype=np.float64)
    if B.shape != (3, 3):
        raise ValueError("Matrix must be 3x3!")

    #Reducing second row
    B[1, :] = B[1, :] - (B[1, 0]/(B[0,0])) * (B[0,:])
    B[2, :] = B[2, :] - (B[2, 0]/(B[0,0])) * (B[0,:])

    #Reducing third row
    B[2, :] = B[2, :] - (B[2, 1]/(B[1,1])) * (B[1,:])
    
    return B

In [37]:
print(reduce_row_echelon3x3(A))

[[ 1.  2.  3.]
 [ 0. -1. -1.]
 [ 0.  0. -4.]]


In [46]:
 # Unit tests 

# Example 1: Identity matrix (already in echelon form)
A1 = np.eye(3)

# Example 2: Simple upper-triangular
A2 = np.array([[2, 3, 1],
               [4, 7, 5],
               [6, 9, 8]])

# Example 3: Matrix with zeros in some places
A3 = np.array([[1, 2, 3],
               [2, 4, 6],   # Notice row 2 is a multiple of row 1
               [1, 1, 1]])

# Example 4: Random integer matrix
np.random.seed(37)  # for reproducibility
A4 = np.random.randint(-5, 6, (3,3))   # values between -5 and 5

# Example 5: Another random float matrix
A5 = np.random.randn(3,3)  # standard normal distribution
for i, A in enumerate([A1, A2, A3, A4, A5], start=1):
    print(f"\nMatrix A{i}:")
    sp.pprint(sp.Matrix(A))
    print()
    print("Row echelon form:")
    sp.pprint(sp.Matrix(reduce_row_echelon3x3(A)))



Matrix A1:
⎡1.0   0    0 ⎤
⎢             ⎥
⎢ 0   1.0   0 ⎥
⎢             ⎥
⎣ 0    0   1.0⎦

Row echelon form:
⎡1.0   0    0 ⎤
⎢             ⎥
⎢ 0   1.0   0 ⎥
⎢             ⎥
⎣ 0    0   1.0⎦

Matrix A2:
⎡2  3  1⎤
⎢       ⎥
⎢4  7  5⎥
⎢       ⎥
⎣6  9  8⎦

Row echelon form:
⎡2.0  3.0  1.0⎤
⎢             ⎥
⎢ 0   1.0  3.0⎥
⎢             ⎥
⎣ 0    0   5.0⎦

Matrix A3:
⎡1  2  3⎤
⎢       ⎥
⎢2  4  6⎥
⎢       ⎥
⎣1  1  1⎦

Row echelon form:
⎡1.0  2.0  3.0⎤
⎢             ⎥
⎢ 0    0    0 ⎥
⎢             ⎥
⎣nan  nan  nan⎦

Matrix A4:
⎡0   1   5⎤
⎢         ⎥
⎢-2  -2  5⎥
⎢         ⎥
⎣0   3   0⎦

Row echelon form:
⎡ 0   1.0  5.0⎤
⎢             ⎥
⎢nan   ∞    ∞ ⎥
⎢             ⎥
⎣nan  nan  nan⎦

Matrix A5:
⎡-0.925859346465875  0.323742703195419   0.665965983883547⎤
⎢                                                         ⎥
⎢-1.75226328120771    1.55766843625814   0.811770648472646⎥
⎢                                                         ⎥
⎣-0.840145442931554  -0.194063450472482  0.26525352324381 ⎦

Row

/tmp/ipykernel_8174/2545768229.py:11: RuntimeWarning: divide by zero encountered in double_scalars
  B[2, :] = B[2, :] - (B[2, 1]/(B[1,1])) * (B[1,:])
/tmp/ipykernel_8174/2545768229.py:11: RuntimeWarning: invalid value encountered in multiply
  B[2, :] = B[2, :] - (B[2, 1]/(B[1,1])) * (B[1,:])
/tmp/ipykernel_8174/2545768229.py:9: RuntimeWarning: divide by zero encountered in double_scalars
  B[1, :] = B[1, :] - (B[1, 0]/(B[0,0])) * (B[0,:])
/tmp/ipykernel_8174/2545768229.py:9: RuntimeWarning: invalid value encountered in multiply
  B[1, :] = B[1, :] - (B[1, 0]/(B[0,0])) * (B[0,:])
/tmp/ipykernel_8174/2545768229.py:10: RuntimeWarning: invalid value encountered in double_scalars
  B[2, :] = B[2, :] - (B[2, 0]/(B[0,0])) * (B[0,:])


## Generalized Row Echelon

In [ ]:
from typing import Optional

# Defininng a tolerance for treating small numbers as zero, to avoid floating point rounding errors


def row_echelon():
    """Given a """