Normal Equation for Optimum parameter : 


![alt text](image.png)

In [1]:
import numpy as np

In [13]:
x = np.array([1,2,3,4,5]).reshape(-1,1)
y = np.array([1,2,3,4,5]).reshape(-1,1)

x0 = np.array([1,1,1,1,1]).reshape(-1,1)

In [14]:
X = np.c_[x0,x]
Y = y

In [15]:
print(X)
print(Y)

[[1 1]
 [1 2]
 [1 3]
 [1 4]
 [1 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [16]:
theta = np.linalg.inv(X.T @ X) @ (X.T @ Y)

In [17]:
print(np.round(theta,2))

[[0.]
 [1.]]


In [25]:
# using randomly generated data 

# Let the line be y = 3 + 7x

theta_true = [3, 7]
n = 100 # samples 
x = 2 * np.random.rand(n, 1)

y = theta_true[0] + theta_true[1] * x + np.random.randn(n, 1)

In [30]:
x0 = np.ones(n).reshape(-1,1)

X = np.c_[x0, x]
Y = y

In [32]:
print(X[:3])
print(Y[:3])

[[1.         0.28583526]
 [1.         1.06067558]
 [1.         1.5493427 ]]
[[ 5.91567448]
 [12.20108601]
 [11.66085445]]


In [34]:
theta = np.linalg.inv(X.T @ X) @ (X.T @ Y)
print(np.round(theta, 2))

[[2.67]
 [7.23]]
